Enable linking views across two Plotters
pyvista/pyvistaqt pull request #133
Opened 2021-11-30 11:56 UTC by p-j-smith

### Overview

Fixes #131 

Allows to link the views of two different Plotters.

### Details

* A `link_views_across_plotters` method has been added to `pyvistaqt.plotting.QtInteractor`. It will a view of the current QtInteractor with specified views of a second QtInteractor.

* I thought creating a new method for this rather than overloading `pyvista.plotting.plotting.BasePlotter` was a little simpler and easier to read, but I'm happy change it if you feel otherwise.

* I havent added an `unlink_views_across_plotters` method as `pyvista.plotting.plotting.BasePlotter.unlink_views` can still be used for this.

* I thought about testing but I'm not too sure how to go about it. Here's the tests for pyvista's `link_views`: https://github.com/pyvista/pyvista/blob/main/tests/plotting/test_plotting.py#L1318-L1338 Would something similar work for `link_views_across_plotters`?

* I've tried it out on something I'm developing and it seems to work okay:

https://user-images.githubusercontent.com/29753790/144042931-244586a5-6cf2-48ea-b1cc-55d985ab913e.mov

2021-12-02 12:21 UTC, p-j-smith commented
Hi, `test_background_plotting_add_callback` is not something I've touched with this PR, but it failed with a timeout error. Would it be possible to restart the tests please?

2021-12-06 12:07 UTC, GuillaumeFavelier requested changes
Hi @p-j-smith and thank you for your great contribution! I tested locally with a very basic example:

```py
import pyvista as pv
from pyvistaqt import BackgroundPlotter

mesh_1 = pv.Cone()
mesh_2 = pv.Cube()

plotter_1 = BackgroundPlotter()
plotter_1.add_mesh(mesh_1)

plotter_2 = BackgroundPlotter()
plotter_2.add_mesh(mesh_2)

plotter_1.link_views_across_plotters(plotter_2)
```

and all works as expected. Also, nice job with the test too.

Maybe something that I noticed is a small 'update lag' for the plotter which is not directly interacted with but I think it's a minor issue and can be dealt with in a follow-up PR.

I restarted the failing CIs and everything is green atm so LGTM except my small question :+1:

2021-12-06 12:33 UTC, p-j-smith commented on tests/test_plotting.py
> +from typing import Type
Sorry about that, I've removed it now

2021-12-06 12:37 UTC, p-j-smith commented
Thanks for your review @GuillaumeFavelier! I've removed the unused import. And fixing the update lag would be really nice, although I have no idea where to start. Do you have any ideas for what might cause the lag?

2021-12-06 12:58 UTC, GuillaumeFavelier commented
> Do you have any ideas for what might cause the lag?

I'm not quite sure. It could be related to the automatic update rate or a delay with Qt events processing for example.

2021-12-06 14:47 UTC, GuillaumeFavelier approved these changes

2021-12-08 13:29 UTC, p-j-smith commented
Hi @GuillaumeFavelier would you mind merging the PR (I don't have permissions to do so), or do we need a second pair of eyes to look over it? Thanks 😄

2021-12-08 13:38 UTC, GuillaumeFavelier commented
@akaszynski can you take a look? Maybe we could merge this before the release, what do you think?

2021-12-14 13:21 UTC, GuillaumeFavelier commented
I'll ahead and merge your work then :)

2021-12-14 13:21 UTC, merged

2021-12-14 13:22 UTC, GuillaumeFavelier commented
Thank you for your contribution @p-j-smith!

2021-12-14 15:47 UTC, p-j-smith commented
Thank you for your review @GuillaumeFavelier !